DuckFast.Web/Areas/Admin/Controllers/ArticlesController.cs
using AutoMapper;
using DuckFast.Common.Services;
using DuckFast.Database.Entities;
using DuckFast.Web.Areas.Admin.Helper;
using DuckFast.Web.Areas.Admin.Models;
using DuckFast.Web.Areas.Admin.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DuckFast.Web.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class ArticlesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IArticleService _articleService;
        private readonly IUserAccountService _userAccountService;
        private readonly ICategoryService _categoryService;

        public ArticlesController(
            IMapper mapper,
            IArticleService articleService,
            IUserAccountService userAccountService,
            ICategoryService categoryService)
        {
            _mapper = mapper;
            _articleService = articleService;
            _userAccountService = userAccountService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index(string search, int category, string author, string status, string sort)
        {
            var articles = await _articleService.GetArticles();
            var users = await _userAccountService.GetUserAccounts();
            var categories = await _categoryService.GetCategories();

            if (author != null)
                articles = articles.Where(x => x.Author!.Id == author);
            
            if (!string.IsNullOrEmpty(search))
                articles = articles.Where(x => x.Title!.Contains(search));

            var viewModel = new ArticlesListViewModel
            {
                Articles = _mapper.Map<IEnumerable<ArticleModel>>(articles),
                SelectListAuthor = new SelectList(users.ToSelectList(x => x.DisplayName, x => x.Id), "Value", "Text"),
                SelectListCategory = new SelectList(categories.ToSelectList(x => x.Name, x => x.Id), "Value", "Text"),
                Search = search,
                Category = category,
                Author = author,
                Status = status,
                Sort = sort
            };

            return View(viewModel!);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var users = await _userAccountService.GetUserAccounts();
            var categories = await _categoryService.GetCategories();
            var article = await _articleService.GetArticle(id);
            var editModel = new ArticleEditViewModel
            {
                Id = id,
                SelectListAuthor = new SelectList(users.ToSelectList(x => x.DisplayName, x => x.Id), "Value", "Text"),
                SelectListCategory = new SelectList(categories.ToSelectList(x => x.Name, x => x.Id), "Value", "Text"),
                Author = article!.Author!.Id,
                Category = article!.Category?.Id ?? 0,
                PrevContent = string.Format("<h2>{0}</h2>{1}", article!.Title, article!.Content),
                Excerpt = article!.Excerpt,
                Slug = article!.Slug,
                Status = article!.Status,
            };
            return View(editModel!);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] ArticleRequestModel articleModel)
        {
            var article = _mapper.Map<Article>(articleModel);

            article.Category = await _categoryService.GetCategory(articleModel.Category);
            article.Author = await _userAccountService.GetUserAccount(articleModel.Author!);

            await _articleService.UpdateArticle(article);

            return RedirectToAction("Edit", new { @id = article.Id });
        }
    }
}

DuckFast.Web/Areas/Admin/Controllers/CategoriesController.cs
using AutoMapper;
using DuckFast.Common.Services;
using DuckFast.Database.Entities;
using DuckFast.Web.Areas.Admin.Models.ViewModels;
using DuckFast.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace DuckFast.Web.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ICategoryService _categoryService;

        public CategoriesController(
           IMapper mapper,
           ICategoryService categoryService)
        {
            _mapper = mapper;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index(int selectedCategory, string search, string sort)
        {
            var categories = await _categoryService.GetCategories();

            CategoriesListViewModel viewModel;

            if (selectedCategory != 0)
            {
                var selected = await _categoryService.GetCategory(selectedCategory);

                viewModel = new CategoriesListViewModel
                {
                    Categories = _mapper.Map<IEnumerable<CategoryModel>>(categories),
                    Search = null,
                    Sort = null,
                    CurrentCategory = _mapper.Map<CategoryModel>(selected)
                };
            }
            else
            {
                if (!string.IsNullOrEmpty(search))
                    categories = categories.Where(x => x.Name!.Contains(search));

                viewModel = new CategoriesListViewModel
                {
                    Categories = _mapper.Map<IEnumerable<CategoryModel>>(categories),
                    Search = search,
                    Sort = sort,
                    CurrentCategory = new(),
                };
            }

            return View(viewModel!);
        }

        [HttpPost]
        public async Task<IActionResult> Update([FromForm] CategoryModel categoryModel)
        {
            await _categoryService.UpdateCategory(_mapper.Map<Category>(categoryModel));

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Add([FromForm] CategoryModel categoryModel)
        {
            await _categoryService.AddCategory(_mapper.Map<Category>(categoryModel));

            return RedirectToAction("Index");
        }
    }
}

DuckFast.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DuckFast.Web</title>
    <meta name="theme-color" content="#7952b3">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text&display=swap" rel="stylesheet">
    <link href="https://fonts.cdnfonts.com/css/inter" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/ckeditor.css">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @@media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
</head>
<body class="bg-light">
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">DuckFast Dashboard</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <span class="navbar-text text-nowrap ps-3">Hello, <strong>Admin</strong></span>
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <a asp-area="Identity" asp-page="/Account/Logout" class="nav-link px-3">Sign out</a>
            </div>
        </div>
    </header>
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">
                                <span data-feather="home"></span>
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Articles" asp-action="Index">
                                <span data-feather="file-text"></span>
                                Articles
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Categories" asp-action="Index">
                                <span data-feather="layers"></span>
                                Categories
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="users"></span>
                                Users
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Reports
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="settings"></span>
                                Settings
                            </a>
                        </li>
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Saved reports</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Current month
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Social engagement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Year-end sale
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/moment.js/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="~/js/admin.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>